### ISSUE TITLE
Multiple runtime exceptions happens when testing suspend functions

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [Kotlin/kotlinx-lincheck#34]
I have a stable and reproducible example of RuntimeExceptions which thrown out when **suspending** functions used together with **kotlin-stdlib-jdk8** https://github.com/vladimir-bukhtoyarov/bucket4j/blob/5.0_try_lincheck/lincheck-tests/src/test/kotlin/io/github/bucket4j/distributed/proxy/optimizers/batch/mock/BatchingAsyncExecutorLincheckTest.kt

It looks as ```kotlin.UninitializedPropertyAccessException``` when **minimizeFailedScenario=true** 
```
= Iteration 1 / 10 =
Execution scenario (parallel part):
| *testBatching(1)  | testBatching(9)   | testBatching(10)  |
| *testBatching(8)  | *testBatching(16) | testBatching(14)  |
| *testBatching(12) | *testBatching(2)  | *testBatching(20) |
| *testBatching(15) | testBatching(18)  | *testBatching(18) |
| testBatching(14)  | *testBatching(3)  | testBatching(16)  |
Execution scenario (post part):
[]

kotlin.UninitializedPropertyAccessException: lateinit property by has not been initialized

	at org.jetbrains.kotlinx.lincheck.ResumedResult.getBy(Result.kt:110)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$getResumedOperations$1.accept(LTS.kt:182)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$getResumedOperations$1.accept(LTS.kt:77)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.getResumedOperations(LTS.kt:181)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.access$getResumedOperations(LTS.kt:77)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$nextByRequest$transitionInfo$1.apply(LTS.kt:95)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$nextByRequest$transitionInfo$1.apply(LTS.kt:77)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.nextByRequest(LTS.kt:89)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.next(LTS.kt:86)
	at org.jetbrains.kotlinx.lincheck.verifier.linearizability.LinearizabilityContext.nextContext(LinearizabilityVerifier.kt:73)
	at org.jetbrains.kotlinx.lincheck.verifier.linearizability.LinearizabilityContext.nextContext(LinearizabilityVerifier.kt:45)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:48)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:49)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:49)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:49)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verifyResultsImpl(AbstractLTSVerifier.kt:40)
	at org.jetbrains.kotlinx.lincheck.verifier.CachedVerifier.verifyResults(CachedVerifier.java:42)
	at org.jetbrains.kotlinx.lincheck.strategy.Strategy.verifyResults(Strategy.java:57)
	at org.jetbrains.kotlinx.lincheck.strategy.stress.StressStrategy.run(StressStrategy.java:75)
	at org.jetbrains.kotlinx.lincheck.LinChecker.runScenario(LinChecker.java:168)
	at org.jetbrains.kotlinx.lincheck.LinChecker.checkImpl(LinChecker.java:103)
	at org.jetbrains.kotlinx.lincheck.LinChecker.lambda$check$0(LinChecker.java:86)
	at java.util.Collections$SingletonList.forEach(Collections.java:4822)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.java:84)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.java:74)
	at io.github.bucket4j.distributed.proxy.optimizers.batch.mock.BatchingAsyncExecutorLincheckTest.runTest(BatchingAsyncExecutorLincheckTest.kt:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

It looks as ```java.lang.IllegalStateException``` when **minimizeFailedScenario=false** Sometimes as 
```
java.lang.IllegalStateException: Cancelled operations should not be processed as the resumed ones

	at org.jetbrains.kotlinx.lincheck.verifier.LTS.invoke(LTS.kt:213)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS.access$invoke(LTS.kt:59)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$nextByCancellation$1.apply(LTS.kt:118)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$nextByCancellation$1.apply(LTS.kt:77)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.nextByCancellation(LTS.kt:114)
	at org.jetbrains.kotlinx.lincheck.verifier.linearizability.LinearizabilityContext.nextContext(LinearizabilityVerifier.kt:68)
	at org.jetbrains.kotlinx.lincheck.verifier.linearizability.LinearizabilityContext.nextContext(LinearizabilityVerifier.kt:45)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:48)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:49)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:49)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verifyResultsImpl(AbstractLTSVerifier.kt:40)
	at org.jetbrains.kotlinx.lincheck.verifier.CachedVerifier.verifyResults(CachedVerifier.java:42)
	at org.jetbrains.kotlinx.lincheck.strategy.Strategy.verifyResults(Strategy.java:57)
	at org.jetbrains.kotlinx.lincheck.strategy.stress.StressStrategy.run(StressStrategy.java:75)
	at org.jetbrains.kotlinx.lincheck.LinChecker.runScenario(LinChecker.java:168)
	at org.jetbrains.kotlinx.lincheck.LinChecker.checkImpl(LinChecker.java:103)
	at org.jetbrains.kotlinx.lincheck.LinChecker.lambda$check$0(LinChecker.java:86)
	at java.util.Collections$SingletonList.forEach(Collections.java:4822)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.java:84)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.java:74)
	at io.github.bucket4j.distributed.proxy.optimizers.batch.mock.BatchingAsyncExecutorLincheckTest.runTest(BatchingAsyncExecutorLincheckTest.kt:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

Could somebody point out what I am doing in the wrong way?

**Comment by vladimir-bukhtoyarov** [comment]
Also I observe sometimes **KotlinNullPointerException**
```
kotlin.KotlinNullPointerException
	at org.jetbrains.kotlinx.lincheck.verifier.LTS.invoke(LTS.kt:200)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS.access$invoke(LTS.kt:59)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$nextByFollowUp$transitionInfo$1.apply(LTS.kt:106)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$nextByFollowUp$transitionInfo$1.apply(LTS.kt:77)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.nextByFollowUp(LTS.kt:102)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.next(LTS.kt:86)
	at org.jetbrains.kotlinx.lincheck.verifier.linearizability.LinearizabilityContext.nextContext(LinearizabilityVerifier.kt:73)
	at org.jetbrains.kotlinx.lincheck.verifier.linearizability.LinearizabilityContext.nextContext(LinearizabilityVerifier.kt:45)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:48)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:49)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:49)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:49)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:49)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verifyResultsImpl(AbstractLTSVerifier.kt:40)
	at org.jetbrains.kotlinx.lincheck.verifier.CachedVerifier.verifyResults(CachedVerifier.java:42)
	at org.jetbrains.kotlinx.lincheck.strategy.Strategy.verifyResults(Strategy.java:57)
	at org.jetbrains.kotlinx.lincheck.strategy.stress.StressStrategy.run(StressStrategy.java:75)
	at org.jetbrains.kotlinx.lincheck.LinChecker.runScenario(LinChecker.java:168)
	at org.jetbrains.kotlinx.lincheck.LinChecker.checkImpl(LinChecker.java:103)
	at org.jetbrains.kotlinx.lincheck.LinChecker.lambda$check$0(LinChecker.java:86)
	at java.util.Collections$SingletonList.forEach(Collections.java:4822)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.java:84)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.java:74)
	at io.github.bucket4j.distributed.proxy.optimizers.batch.mock.BatchingAsyncExecutorLincheckTest.runTest(BatchingAsyncExecutorLincheckTest.kt:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Comment by ndkoval** [comment]
@vladimir-bukhtoyarov, could you please check whether the test fails event if cancellation is disabled for `suspend` functions? Please, use the code below:
 
```
@Operation(cancellableOnSuspension = false)
```

**Comment by vladimir-bukhtoyarov** [comment]
@ndkoval I [have tried](https://github.com/vladimir-bukhtoyarov/bucket4j/commit/5356072a291321606d02cff16718b25b2221d4de) still failing, but errors did not stop and look the same

```
= Iteration 1 / 10 =
Execution scenario (parallel part):
| testBatching(1)  | testBatching(9)  | testBatching(10) |
| testBatching(8)  | testBatching(16) | testBatching(14) |
| testBatching(12) | testBatching(2)  | testBatching(20) |
| testBatching(15) | testBatching(18) | testBatching(18) |
| testBatching(14) | testBatching(3)  | testBatching(16) |
Execution scenario (post part):
[]

kotlin.UninitializedPropertyAccessException: lateinit property by has not been initialized

	at org.jetbrains.kotlinx.lincheck.ResumedResult.getBy(Result.kt:110)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$getResumedOperations$1.accept(LTS.kt:182)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$getResumedOperations$1.accept(LTS.kt:77)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.getResumedOperations(LTS.kt:181)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.access$getResumedOperations(LTS.kt:77)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$nextByRequest$transitionInfo$1.apply(LTS.kt:95)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State$nextByRequest$transitionInfo$1.apply(LTS.kt:77)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.nextByRequest(LTS.kt:89)
	at org.jetbrains.kotlinx.lincheck.verifier.LTS$State.next(LTS.kt:86)
	at org.jetbrains.kotlinx.lincheck.verifier.linearizability.LinearizabilityContext.nextContext(LinearizabilityVerifier.kt:73)
	at org.jetbrains.kotlinx.lincheck.verifier.linearizability.LinearizabilityContext.nextContext(LinearizabilityVerifier.kt:45)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:48)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verify(AbstractLTSVerifier.kt:49)
	at org.jetbrains.kotlinx.lincheck.verifier.AbstractLTSVerifier.verifyResultsImpl(AbstractLTSVerifier.kt:40)
	at org.jetbrains.kotlinx.lincheck.verifier.CachedVerifier.verifyResults(CachedVerifier.java:42)
	at org.jetbrains.kotlinx.lincheck.strategy.Strategy.verifyResults(Strategy.java:57)
	at org.jetbrains.kotlinx.lincheck.strategy.stress.StressStrategy.run(StressStrategy.java:75)
	at org.jetbrains.kotlinx.lincheck.LinChecker.runScenario(LinChecker.java:168)
	at org.jetbrains.kotlinx.lincheck.LinChecker.checkImpl(LinChecker.java:103)
	at org.jetbrains.kotlinx.lincheck.LinChecker.lambda$check$0(LinChecker.java:86)
	at java.util.Collections$SingletonList.forEach(Collections.java:4822)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.java:84)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.java:74)
	at io.github.bucket4j.distributed.proxy.optimizers.batch.mock.BatchingAsyncExecutorLincheckTest.runTest(BatchingAsyncExecutorLincheckTest.kt:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)


Process finished with exit code 255
```

**Comment by ndkoval** [comment]
@vladimir-bukhtoyarov I've tried to reproduce the error but was unable to build the project:

```
Cannot resolve com.github.vladimir-bukhtoyarov:rolling-metrics-dropwizard:3.0.0-RC2
Cannot resolve com.github.vladimir-bukhtoyarov:rolling-metrics-core:3.0.0-RC2
Cannot resolve com.github.vladimir-bukhtoyarov:rolling-metrics-dropwizard:3.0.0-RC2
Cannot resolve com.github.vladimir-bukhtoyarov:rolling-metrics-core:3.0.0-RC2
```

May I ask you to either provide a step-by-step guide to build the project or move your failing example our of the project, please?

**Comment by vladimir-bukhtoyarov** [comment]
@ndkoval 

I am sorry. I have fixed dependency for rolling-metrics, so now I should not have problems with missed dependencies.

**Comment by ndkoval** [comment]
@vladimir-bukhtoyarov I've taken a closer look at your code, and have realized that your test is incorrect. You should wrap `testBatching` operation with `runBlocking { .. }` since its suspension does not mean that the operation is blocked -- it completes eventually. 

Also, do not forget to make `MockAsyncCommandExecutor#executor` static; otherwise, a new executor along with a new thread is allocated on each invocation, and the test fails with `OoME`.
