### ISSUE TITLE
Error message in wrong generator configuration

### ISSUE THREAD

**Issue by aschugunov** [Kotlin/kotlinx-lincheck#38]
When I use a configuration like:
`@Param(gen = IntGen.class, conf = "3,5")`

I am getting an error - "Configuration should have two arguments (begin and end) separated by **comma**"

```
java.lang.IllegalStateException: Cannot create parameter gen

	at org.jetbrains.kotlinx.lincheck.CTestStructure.createGenerator(CTestStructure.java:164)
	...................
eflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.kotlinx.lincheck.CTestStructure.createGenerator(CTestStructure.java:162)
	... 70 more
Caused by: java.lang.IllegalArgumentException: Configuration should have two arguments (begin and end) separated by comma
	at org.jetbrains.kotlinx.lincheck.paramgen.IntGen.<init>(IntGen.java:48)
```

I believe it should be **colon**

version 2.7.1

**Comment by alefedor** [comment]
Thank you, seems like this was silently fixed for all generators after your issue
